name: Restart OpenShift Build

on:
  push:
    branches:
      - main  # 트리거할 브랜치




jobs:
  restart_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout jetty Repository
        uses: actions/checkout@v2
       

      - name: Set up OpenShift CLI
        uses: redhat-actions/oc-installer@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          
          
      - name: Set up OpenShift Configuration
        run: |
          mkdir -p $HOME/.kube
          echo "$OPENSHIFT_CONFIG" > $HOME/.kube/config
        env:
          OPENSHIFT_CONFIG: ${{ secrets.OPENSHIFT_CONFIG }}

      - name: Log into OpenShift Cluster
        run: oc login ${{ secrets.OPENSHIFT_API_ENDPOINT}} --username ${{secrets.ROSA_ID}} --password ${{secrets.ROSA_PASSWORD}}


      - name: Restart OpenShift Admin Build
        run: oc start-build jetty-public --from-dir=$GITHUB_WORKSPACE

  # ... 다른 빌드 작업들 ...
